removed second window on `tmux-ss` and run if a `tmux-ss.sh` exists on the directory

diff --git a/Scripts/tmux-ss b/Scripts/tmux-ss
--- a/Scripts/tmux-ss
+++ b/Scripts/tmux-ss
@@ -1,39 +1,45 @@
 #!/bin/sh
 
+# tmux setup session
+
 if [ -z "$1" ]; then
-  echo "Missing directory. Usage: $0 <directory>"
-  exit 1
+    echo "Missing directory. Usage: $0 <directory>"
+    exit 1
 fi
 
-DEV_DIR=$(realpath "$1")
-if [ ! -d "$DEV_DIR" ]; then
-  echo "Invalid directory. Not found: $DEV_DIR"
-  exit 1
+SESSION_DIR=$(realpath "$1")
+if [ ! -d "$SESSION_DIR" ]; then
+    echo "Invalid directory. Not found: $SESSION_DIR"
+    exit 1
 fi
 
-SESSION=$(basename "$1")
+SESSION_NAME=$(basename "$1")
 
 # Session
-tmux new-session -d -s $SESSION -A
+tmux new-session -d -s $SESSION_NAME -A
 
 # Main window 1 :: Setup
-if [ -f "$DEV_DIR/.nvimsession" ]; then
-  tmux send-keys -t $SESSION "cd $DEV_DIR;nvim -S .nvimsession;clear" C-m
+if [ -f "$SESSION_DIR/.nvimsession" ]; then
+    tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;nvim -S .nvimsession;clear" C-m
 else
-  tmux send-keys -t $SESSION "cd $DEV_DIR;nvim;clear" C-m
+    tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;nvim;clear" C-m
 fi
 
-tmux split-pane -t $SESSION
-tmux send-keys -t $SESSION "cd $DEV_DIR;clear" C-m
+tmux split-pane -t $SESSION_NAME
+tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m
 # Main window 1 :: Maximize editor
-tmux select-pane -t $SESSION.+1
-tmux resize-pane -Z -t $SESSION
+tmux select-pane -t $SESSION_NAME.+1
+tmux resize-pane -Z -t $SESSION_NAME
 
 # Sub window 2 :: Setup
-tmux new-window -t $SESSION
-tmux send-keys -t $SESSION "cd $DEV_DIR;clear" C-m
+#tmux new-window -t $SESSION_NAME
+#tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m
+#
+#tmux split-pane -t $SESSION_NAME
+#tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m
+#
+#tmux select-window -t $SESSION_NAME:1
 
-tmux split-pane -t $SESSION
-tmux send-keys -t $SESSION "cd $DEV_DIR;clear" C-m
-
-tmux select-window -t $SESSION:1
+if [ -f "$SESSION_DIR/tmux-ss.sh" ]; then
+    source "$SESSION_DIR/tmux-ss.sh"
+fi
